### PR TITLE
Fix BOM issue

### PR DESCRIPTION
**Pull request by Athelena**
Had a quick play and this is what I have, works for me 🤷 

Fix for #21

### CODE REVIEW

**Comment by hugoledoux** [comment]
You wrote many lines just to warn the user that there is a BOM header, right?

If we add to open() the `encoding='utf-8-sig'` then it works for all files, with and without BOM header.

Question is: BOM doesn't seem to be an error so I'd just not warn users at all and handle it.

The files cjio will save will always be without the BOM.
Agreed?

**Comment by Athelena** [comment]
I agree that if you just open it with `encoding='utf-8-sig'` it's fine and any output from cjio will not have it. At the same time, technically speaking, a BOM is not allowed and if the user only uses cjio for info, for example, they'll never know that they have an "illegal" JSON which can cause issues later down the line. Anyways I don't insist, I just think it's a useful warning.

**Comment by hugoledoux** [comment]
But my question is: is it really "illegal"?

**Comment by Athelena** [comment]
According to this passionate [answer](https://stackoverflow.com/a/38036753/2192213), yes 😅

**Comment by hugoledoux** [comment]
OK instead of asking you I went looking for the answer:

from [the official specs](https://tools.ietf.org/html/rfc7159#section-8.1):

    > Implementations MUST NOT add a byte order mark to the beginning of a JSON text.  In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

**Comment by Athelena** [comment]
Thanks for having faith in me 😏

**Comment by hugoledoux** [comment]
well was more meant as I should check myself and not ask you to...

but anyway, I'll just add the handling and make it silent, "in the interests of interoperability", innit?

**Comment by Athelena** [comment]
Cool 👍

**Comment by hugoledoux** [comment]
added to merge() too baf169a2a283cae4bf9f9b9e26ff83b51646ff7e

**Pull request closed without merging**
